### ISSUE TITLE
How to generate label for single oracle?

### ISSUE THREAD

**Issue by gyholee** [EdinburghNLP/Refresh#12]

**Comment by gyholee** [comment]
I try to experiment with anonymized CNN/Daily data, but there is no proper label data that is open.
How did you create the single oracle label?
In the paper, it is said that it was created by greedy method, How did you use Rouge score?
Rouge-2 Recall or Rouge2-F-score or combination?

**Comment by shashiongithub** [comment]
We don't create single oracle, we create multiple Oracle labels. These labels have been released. You could use top ranked one as the best single oracle label. 

We use mean of R1, R2 and RL F scores.

**Comment by gyholee** [comment]
okay, thanks. 
If so, how did you make file such as  cnn.test.label.singleoracle, cnn.training.label.singleoracle etc?

**Comment by shashiongithub** [comment]
I have not shared that code, it uses the original PyRouge to generate multiple oracles as described in the paper. If you need to create these files for your own dataset, email me. One of my friend has written a faster version of this which approximates these scores.

**Comment by gyholee** [comment]
After listening to your explanation and looking at the papers and data again, I understood what I missed.
Thank you for releasing good papers and data.

**Comment by shashiongithub** [comment]
Thanks!
