### ISSUE TITLE
Pyrouge

### ISSUE THREAD

**Issue by prateekverma1** [EdinburghNLP/Refresh#13]
Hi Shashi,

While running the code, after 1 epoch is done, when it is just about to write the final validation summaries, I get the following error - 

> File "document_summarizer_training_testing.py", line 212, in train
>     rouge_score = rouge_generator.get_full_rouge(FLAGS.train_dir+"/model.ckpt.epoch-"+str(epoch)+".validation-summary-topranked", "validation")
>   File "/datadrive/prateek/Summarization/Refresh/reward_utils.py", line 199, in get_full_rouge
>     rouge_score = _rouge(system_dir, gold_summary_directory)
>   File "/datadrive/prateek/Summarization/Refresh/reward_utils.py", line 38, in _rouge
>     output = r.convert_and_evaluate(rouge_args="-e /address/to/rouge/data/directory/rouge/data -a -c 95 -m -n 4 -w 1.2")
>   File "/datadrive/miniconda3/envs/summly/lib/python2.7/site-packages/pyrouge/Rouge155.py", line 361, in convert_and_evaluate
>     rouge_output = self.evaluate(system_id, rouge_args)
>   File "/datadrive/miniconda3/envs/summly/lib/python2.7/site-packages/pyrouge/Rouge155.py", line 336, in evaluate
>     rouge_output = check_output(command).decode("UTF-8")
>   File "/datadrive/miniconda3/envs/summly/lib/python2.7/subprocess.py", line 223, in check_output
>     raise CalledProcessError(retcode, cmd, output=output)
> subprocess.CalledProcessError: Command '[u'/datadrive/prateek/Summarization/github-pyrouge/pyrouge/tools/ROUGE-1.5.5/ROUGE-1.5.5.pl', '-e', '/address/to/rouge/data/directory/rouge/data', '-a', '-c', '95', '-m', '-n', '4', '-w', '1.2', u'-m', u'/tmp/tmpFdvDy4/rouge_conf.xml']' returned non-zero exit status 2
> 

To me it seems like a pyrouge related error. I have installed Pyrouge using the instructions mentioned here -
https://stackoverflow.com/questions/47045436/how-to-install-the-python-package-pyrouge-on-microsoft-windows/47045437#47045437

Is the error due to Pyrouge, if so how would you recommend I install Pyrouge?

**Comment by shashiongithub** [comment]
i think you forgot to set '-e', '/address/to/rouge/data/directory/rouge/data'.

**Comment by prateekverma1** [comment]
Thanks a lot! That worked.
