### ISSUE TITLE
 What is the function of the weights in the code.

### ISSUE THREAD

**Issue by Limtle** [EdinburghNLP/Refresh#22]
Hi Shashi,
In paper , I can't find the description about what is the function of the weights. But I saw it used in the code . Can you give me some information about what the weight doing. Thank you.

**Comment by shashiongithub** [comment]
Could you please elaborate on which weights are you talking about? Lines in the paper or code?

**Comment by Limtle** [comment]
Hi Shashi,
I am confused about weight_placeholder.
![default](https://user-images.githubusercontent.com/47511735/52902384-cb392780-324a-11e9-8e70-88f0741e5cd1.PNG)

**Comment by shashiongithub** [comment]
Ohh, this one is just used for masking. In a batch some document could be of smalled length. Weights (1 or 0) shows which sentences/predictions to ignore when assembling the summary or calculating the loss function.
