### ISSUE TITLE
some clarification in estimate_multiple_orcales.py

### ISSUE THREAD

**Issue by venkattrj** [EdinburghNLP/Refresh#24]
Hi Shashi,
   Thanks for providing oracle generation script. while going through estimate_multiple_orcales.py I noticed that files are not considered if their name is not starting with numbers and only a few portions of the dataset is considered for multiple Oracle. can you please explain the reason behind the decision 

![screenshot 2019-02-28 at 6 06 07 pm](https://user-images.githubusercontent.com/12130344/53567425-33f69d00-3b85-11e9-847c-1f1024074f53.png)
![screenshot 2019-02-28 at 6 17 54 pm](https://user-images.githubusercontent.com/12130344/53567426-33f69d00-3b85-11e9-96f3-d8b2d6aaebcf.png)

**Comment by shashiongithub** [comment]
Hi venkatrj,

it was improved by a friend to use Google's implementation of rouge. Feel free to modify it as it fits.
