### ISSUE TITLE
training set mainbody problem

### ISSUE THREAD

**Issue by Limtle** [EdinburghNLP/Refresh#29]
Hi Shashi,
Because i try to use bert sentence embedding in your code. So i need Original training sentence without preprocessed. But I don't have a trianing mainbody for your dataset. Can I have the trianing mainbody  ?

Thanks for your help.

**Comment by shashiongithub** [comment]
Try this: https://cs.nyu.edu/~kcho/DMQA/

or 

https://github.com/abisee/cnn-dailymail
