### ISSUE TITLE
Demo Code

### ISSUE THREAD

**Issue by sai-prasanna** [EdinburghNLP/Refresh#6]
Can you share the demo code ? 

For my purposes a quick python api to text -> summary API of it would be helpful.

I am comparing a bunch of summary methods qualitatively, want to evaluate your retrained model.

**Comment by shashiongithub** [comment]
Could you write me an email, I could send you the demo code.

**Comment by sai-prasanna** [comment]
Thanks, sent you an email. Will close this issue.

**Comment by ShirleyHan6** [comment]
Can I get the demo code also? I am performing some tasks similar to @sai-prasanna. 

Thanks.

Regards,
Shirley

**Comment by shashiongithub** [comment]
drop me an email.

**Comment by ShirleyHan6** [comment]
Received!
Thanks!
